### PR TITLE
Shak/newcontrols

### PR DESCRIPTION
**Pull request by FourierTransformer**
so yeah, only two weapons. Kept the rest of the system the same. Talked with @AOEChamp, and decided to not heavily modify controls, so when/if we add all the weapons back, people already know how to use them.

### CODE REVIEW

**Comment by bkern24** [comment]
So is this better than what I made a pull request for two days ago? I did this already

**Comment by FourierTransformer** [comment]
They didn't merge with develop? Crap. I dunno, it's maybe 6 lines of
modification. I'm not sure what yours does. What does yours do?

**Comment by JaredPoetter** [comment]
I guess that we should not merge things in until tonight's meeting unless you guys can figure out what you have to do to resolve the double implementation.

**Comment by bkern24** [comment]
I have been waiting for it to merge..... I simply commented out weapon switching, and then if left clicked "fire" melee, and if right clicked fire doomsbow.

**Pull request merged**
