### PR TITLE
READ COMMENT BEFORE MERGING

### PR DESCRIPTION
**Pull request by bkern24**
Melee Monster Faster, and no sword. But they only do 5 damage for touching you. If you set it 20 they kill you crazy fast.

PLEASE test branch if this will work, if not do not merge

### CODE REVIEW

**Comment by bkern24** [comment]
So does no one care?

**Comment by AOEChamp** [comment]
We could set the dmage at 20 and then have a cooldown on their attack. So
they can only deal damage every 1-3 seconds.

**Comment by FourierTransformer** [comment]
also, it seems as if they still have trouble landing a hit at times. I'm not quite sure what that's about.

**Comment by bkern24** [comment]
@AOEChamp  I was thinking that but then if you ran into them for 2 seconds they wouldn't do any damage, I guess its more of how we want to design it.

@FourierTransformer Well they have no sword so now its all up to the physics and if you touch them

**Comment by FourierTransformer** [comment]
just played around with it some more. I feel the 5 damage likely isn't enough, so I wasn't sure if I was being hit. This time I noticed the knockback they do and I think it should do a little more damage - maybe 10 or 15. hmmm

**Comment by FourierTransformer** [comment]
actually, does the health bar not update after every hit? I'll let a group of them at me for a bit, then I'll see the health drop significantly.

**Comment by bkern24** [comment]
Well its when they hit you, and then separate from you to be exact. If you want modify the damage you can change it in the Monsters.xml under meleemonster and its basedamage

**Comment by FourierTransformer** [comment]
ah, the separation might be what does it. 'cause when they group it usually gets kinda funky. Then BAM health goes down. Overall, I do think it's more effective than before!

**Comment by bkern24** [comment]
Its still weird though as I apply the damage when they collide and then don't allow them to collide again until they separate... Maybe the physics system runs after the gamelogic system and so its off a frame?

**Comment by FourierTransformer** [comment]
hmmmm that might explain it. @AOEChamp might know a bit more on how that works...

**Comment by AOEChamp** [comment]
It updates immediately for me. I don't think this is going to work though. They run into you and instakill you with repeat damage. Also, if you get backed into a corner, it's over.

Why not bring back swords, but use the new implementation(like the player sword)

**Comment by bkern24** [comment]
I'm fine with either way but if we go the sword route the monster would have to be a bit more intelligent. Right now they just swing the sword whenever their cooldown is done.

**Comment by AOEChamp** [comment]
Pretty sure they only swing when in range, which is fine. If not, it's an
easy modification

**Comment by bkern24** [comment]
Okay well if we would rather have that I can make a new branch for people to test out with them to use the swords.....

**Pull request merged**
